channels:
  - conda-forge

dependencies:
  - python=3.11.6
  - pip
  - osmnx=1.9.3
  - matplotlib=3.8.4
  - sphinx=7.3.7
  - python-igraph=0.10.4
  - geopandas=0.14.4
  - ffmpeg=5.1.2
  - pointpats=2.4.0
  - pip:
      - mesa==2.1.0
      - mesa-geo==0.7.1
